name: Check
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.0

      - name: run tests
        run: python ./tests.py -v
